version: "2"
run:
  concurrency: 2
  go: '1.25'
  timeout: 1m

linters:
  enable-all: true
  disable:
    - depguard
    - wrapcheck
    - mnd
    - varnamelen

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/quarks-tech)
      - prefix(github.com/quarks-tech/protoevent-go)
      - blank
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/quarks-tech/protoevent-go
  lll:
    line-length: 180